/**
 * 用户管理设置页的词典（`auth` 命名域，zh/en 成对）。
 * 错误文案按 host 稳定错误码命名（users.error.<code>），client 直接按码查表。
 */

export const USERS_DICT_ZH: Record<string, string> = {
  "users.nav": "用户管理",
  "users.title": "用户管理",
  "users.subtitle": "管理 dsh-auth 的登录用户（users.yaml）",
  "users.loading": "加载中…",
  "users.unavailable": "当前为 token 模式，用户管理不可用（仅 password 模式支持）。",
  "users.loadError": "用户列表加载失败。",
  "users.retry": "重试",
  "users.you": "当前用户",
  "users.admin": "管理员",
  "users.disabled": "已禁用",
  "users.totpOn": "TOTP",
  "users.changePassword": "修改密码",
  "users.newPassword": "新密码",
  "users.save": "保存",
  "users.cancel": "取消",
  "users.enable": "启用",
  "users.disable": "禁用",
  "users.delete": "删除",
  "users.confirmDelete": "确认删除",
  "users.totpEnable": "启用 TOTP",
  "users.totpDisable": "停用 TOTP",
  "users.totpSecretTitle": "新 TOTP 密钥（只显示这一次）",
  "users.totpSecretHint": "把 base32 密钥或 otpauth 链接添加到认证器应用，然后用登录验证。",
  "users.dismiss": "知道了",
  "users.addTitle": "添加用户",
  "users.username": "用户名",
  "users.password": "密码",
  "users.add": "添加",
  "users.empty": "还没有用户。",
  "users.note": "禁用或删除只阻止新的登录；已签发的会话在过期前仍然有效。",
  "users.noteNonAdmin": "只有管理员可以添加或管理其他用户；你可以修改自己的密码。",
  "users.error.unauthorized": "会话已失效，请刷新页面重新登录。",
  "users.error.forbidden": "没有权限：仅管理员可执行此操作。",
  "users.error.duplicate": "用户名已存在。",
  "users.error.invalid_username": "用户名格式非法（字母或数字开头，可含 . _ -）。",
  "users.error.empty_password": "密码不能为空。",
  "users.error.not_found": "用户不存在。",
  "users.error.self_target": "不能禁用或删除当前登录的用户。",
  "users.error.last_enabled": "至少要保留一个可用用户。",
  "users.error.totp_exists": "该用户已有 TOTP 密钥（先停用再重新启用）。",
  "users.error.user_store_unavailable": "用户文件暂不可用，请稍后再试。",
  "users.error.invalid_entry": "文件内容有非法行，未导入任何用户（见下方明细）。",
  "users.error.no_entries": "没有可导入的条目。",
  "users.error.too_many_entries": "单次最多导入 100 个用户。",
  "users.error.import_file_not_found": "服务器上找不到该文件（需为服务器上 .txt 的绝对路径）。",
  "users.error.import_file_too_large": "文件超过 256 KiB 上限。",
  "users.error.body_too_large": "内容超过大小上限。",
  "users.error.network": "网络错误，请稍后再试。",
  "users.error.unknown": "操作失败。",
  "users.importTitle": "批量导入（txt）",
  "users.importHint": "每行一个：用户名,密码；空行与 # 开头的行会跳过。",
  "users.importModeLocal": "本地文件",
  "users.importModePath": "服务器路径",
  "users.importPathLabel": "服务器文件绝对路径",
  "users.importPathHint": "服务器上 .txt 文件的绝对路径（不超过 256 KiB）。",
  "users.importChooseFile": "选择 txt 文件",
  "users.importRun": "导入",
  "users.importSuccess": "成功导入 {n} 个用户。",
  "users.importFailures": "失败明细：",
  "users.importLine": "第 {line} 行",
};

export const USERS_DICT_EN: Record<string, string> = {
  "users.nav": "User Management",
  "users.title": "User Management",
  "users.subtitle": "Manage dsh-auth sign-in users (users.yaml)",
  "users.loading": "Loading…",
  "users.unavailable": "User management is unavailable in token mode (password mode only).",
  "users.loadError": "Failed to load the user list.",
  "users.retry": "Retry",
  "users.you": "you",
  "users.admin": "admin",
  "users.disabled": "disabled",
  "users.totpOn": "TOTP",
  "users.changePassword": "Change password",
  "users.newPassword": "New password",
  "users.save": "Save",
  "users.cancel": "Cancel",
  "users.enable": "Enable",
  "users.disable": "Disable",
  "users.delete": "Delete",
  "users.confirmDelete": "Confirm delete",
  "users.totpEnable": "Enable TOTP",
  "users.totpDisable": "Disable TOTP",
  "users.totpSecretTitle": "New TOTP secret (shown only once)",
  "users.totpSecretHint":
    "Add the base32 secret or otpauth URI to the authenticator app, then verify by signing in.",
  "users.dismiss": "Done",
  "users.addTitle": "Add user",
  "users.username": "Username",
  "users.password": "Password",
  "users.add": "Add",
  "users.empty": "No users yet.",
  "users.note":
    "Disabling or deleting blocks new sign-ins only; issued sessions stay valid until they expire.",
  "users.noteNonAdmin":
    "Only admins can add or manage other users; you can change your own password.",
  "users.error.unauthorized": "Session expired; refresh the page and sign in again.",
  "users.error.forbidden": "Permission denied: admins only.",
  "users.error.duplicate": "Username already exists.",
  "users.error.invalid_username": "Invalid username (start with a letter or digit; . _ - allowed).",
  "users.error.empty_password": "Password must not be empty.",
  "users.error.not_found": "User not found.",
  "users.error.self_target": "Cannot disable or delete the signed-in user.",
  "users.error.last_enabled": "Keep at least one enabled user.",
  "users.error.totp_exists": "User already has a TOTP secret (disable it first).",
  "users.error.user_store_unavailable": "User store unavailable; try again later.",
  "users.error.invalid_entry": "The file contains invalid lines; nothing was imported (see below).",
  "users.error.no_entries": "Nothing to import.",
  "users.error.too_many_entries": "At most 100 users per import.",
  "users.error.import_file_not_found":
    "File not found on the server (must be an absolute path to a .txt file).",
  "users.error.import_file_too_large": "File exceeds the 256 KiB limit.",
  "users.error.body_too_large": "Content exceeds the size limit.",
  "users.error.network": "Network error; try again later.",
  "users.error.unknown": "Operation failed.",
  "users.importTitle": "Batch import (txt)",
  "users.importHint": "One per line: username,password; empty lines and # comments are skipped.",
  "users.importModeLocal": "Local file",
  "users.importModePath": "Server path",
  "users.importPathLabel": "Absolute file path on the server",
  "users.importPathHint": "Absolute path of a .txt file on the server (at most 256 KiB).",
  "users.importChooseFile": "Choose a txt file",
  "users.importRun": "Import",
  "users.importSuccess": "Imported {n} users.",
  "users.importFailures": "Failures:",
  "users.importLine": "line {line}",
};

/**
 * 错误码 → 本地化文案；码缺失（词典未覆盖）时回落 generic。
 * users-section 与 user-import 共用。
 */
export function userErrorText(t: (key: string) => string, code: string): string {
  const key = `users.error.${code}`;
  const text = t(key);
  return text === key ? t("users.error.unknown") : text;
}
